# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4639f7b587916be74fb765dba4089732b9d213006922e683da5caf3b324645e9b06b22cc811eba8d4f6fe4c5b48e7338b2e87e140e656bc13f4932825babc3b2

test:
  secret_key_base: c7515645925f5d0985c5f6100fc739c76d42e3cb2a346faf49ef95f014ade1ec2157afdb38062ada55ca04e324f686b94c20d75432678d7bc15c71c2506804db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
